%{
%}

%token          EOF LPAREN RPAREN LBRACKET RBRACKET COLON RULE_COND SUBTRACT NOT_EQ ADD MULT EQ RTARROW COMMA DOT APOSTROPHE SEMICOLON 
%token <int>    INTEGER
%token <string> CONSTANT
%token <string> VARIABLE
